version: '3'

services:
  node1:
    image: funkypenguin/Deploycoin
    container_name: Deploytest-node1
    volumes:
      - ../Deploycoind:/var/lib/Deploycoind/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: funkypenguin/Deploycoin
#    container_name: Deploytest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: funkypenguin/Deploycoin
#    container_name: Deploytest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

